Select *
from [Customers]..customers
--total revenue generated by male and female
Select gender,sum(purchase_amount) as revenue
from [Customers]..customers
group by gender
--discount applied but still higher purchase customers
Select customer_id,purchase_amount
from [Customers]..customers
where discount_applied='yes' and purchase_amount>=(select AVG (purchase_amount)from [Customers]..customers)
--top products with highest review rating
Select top 5 item_purchased,ROUND(AVG(review_rating),2) as 'Average Product Rating'
from [Customers]..customers
group by item_purchased
order by AVG(review_rating) desc
--comparing average standard and express shipping amount
Select shipping_type,AVG(purchase_amount)
from [Customers]..customers
where shipping_type in ('standard','express')
group by shipping_type
--Comparing subscribed and unsubscribed customers in terms of total revenue generation
Select subscription_status,count(customer_id) as 'Total Customers',sum(purchase_amount)as 'Total Revenue',
AVG(purchase_amount) as' Avg Spend',concat(SUM(purchase_amount) * 100 / SUM(SUM(purchase_amount)) OVER (),'%')
        as 'Revenue Percent'
from [Customers]..customers
group by subscription_status
order by sum(purchase_amount),AVG(purchase_amount)desc

--top products with highest percentage of purchases with discounts applied
Select Top 6 item_purchased,
100*sum(case when discount_applied='yes' then 1 else 0 end)/count(*) as 'discount rate'
from [Customers]..customers
group by item_purchased
order by 'discount rate' desc
--segmenting customers in terms of new,returning and loyal 
with customer_type as (
select customer_id,previous_purchases,
case
when previous_purchases =1 then'yes'
when previous_purchases between 2 and 20  then 'returning'
else 'loyal'
end as customer_segment
from [Customers]..customers
)
select customer_segment,count(*) as 'total customers'
from customer_type
group by customer_segment
--top 3 most purchased products 
With item_counts as (
Select category,item_purchased,count(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id)DESC) as item_rank
from [Customers]..customers
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;
--checking if repeating customers more than 5 are subscribers
Select subscription_status,
count(customer_id) as 'Repeat buyers'
from [Customers]..customers
where previous_purchases>5
group by subscription_status 
--revenue contribution by each age group
Select sum(purchase_amount) as 'Total Renevue',age_group
from [Customers]..customers
group by age_group
order by 'Total Renevue' desc

